In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import cv2

from PIL import Image

In [2]:
def viewImage(image, name_of_window):
    cv2.namedWindow(name_of_window, cv2.WINDOW_NORMAL)
    cv2.imshow(name_of_window, image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()  

In [3]:
import cv2, time
video = cv2.VideoCapture(0)
check, frame = video.read()
time.sleep(1)
cv2.imshow('Capture', frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

In [6]:
import cv2, time
video = cv2.VideoCapture(0)
a = 1
while True:
    a = a+1
    check, frame = video.read()    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('Capture', gray)
    key = cv2.waitKey(1)
    
    if key == ord('q'):
        break      
print(f'No of frames captured : {a}')
video.release()
cv2.destroyAllWindows()

No of frames captured : 375


In [9]:
# step 1 : import haarcasede xml file
face_classifier = cv2.CascadeClassifier('.\Haarcascades\haarcascade_frontalface_default.xml')
#eye_classifier = cv2.CascadeClassifier('.\Haarcascades\haarcascade_eye.xml')

img = cv2.imread('sample_image.jpeg',1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors = 5)

print(type(faces))
print(faces)

# co-ordinates

for (x,y,w,h) in faces:
    img= cv2.rectangle(img, (x,y),(x+w, y+h), (0,255,0),3)
    
cv2.imshow('face detect', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[1084  438  351  351]
 [ 411  471  328  328]
 [1124  830  218  218]]


In [13]:
# step 1 : import haarcasede xml file
face_classifier = cv2.CascadeClassifier('.\Haarcascades\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('.\Haarcascades\haarcascade_eye.xml')

img = cv2.imread('sample_image.jpeg',1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors = 5)

print(type(faces))
print(faces)

# co-ordinates

for (x,y,w,h) in faces:
    img= cv2.rectangle(img, (x,y),(x+w, y+h), (0,255,0),3)
    
    roi_gray = gray_img[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey),(ex+ew, ey+eh),(0,255,111),2)
           
    
cv2.imshow('face & eye detect', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[1084  438  351  351]
 [ 411  471  328  328]
 [1124  830  218  218]]


In [ ]:
# real time example

In [16]:
# haarcascades means we are giving training to our system/machine to identify such images 

face_cascade = cv2.CascadeClassifier('.\Haarcascades\haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('.\Haarcascades\haarcascade_eye.xml')

def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.05, minNeighbors = 5)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w, y+h), (0,255,0),3)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes=eye_cascade.detectMultiScale(roi_gray,1.1,2)
    
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey),(ex+ew, ey+eh),(0,255,111),2)
    return frame
# using webcam to detect my face and eyes

video = cv2.VideoCapture(0)
while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    detection = detect(gray, frame)
    cv2.imshow('my face and eye detect by webcam', detection)
    
    key = cv2.waitKey(1)
    if key ==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

In [ ]:
# real time example 2


In [19]:
body_classifier = cv2.CascadeClassifier('.\Haarcascades\haarcascade_fullbody.xml')

cap = cv2.VideoCapture('.\Images\walking.avi')

while cap.isOpened():
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    bodies = body_classifier.detectMultiScale(gray, 1.2,3)
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w, y+h), (0,255,255),2)
        cv2.imshow('Walking people on the road', frame)
        
    if cv2.waitKey(1)==13:
        break
cap.release()
cv2.destroyAllWindows()

In [21]:
import cv2, time

body_classifier = cv2.CascadeClassifier('.\Haarcascades\haarcascade_car.xml')

cap = cv2.VideoCapture('.\Images\cars.avi')

while cap.isOpened():
    time.sleep(0.05)
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    bodies = body_classifier.detectMultiScale(gray, 1.2,3)
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w, y+h), (0,255,255),2)
        cv2.imshow('Car is running on the highway', frame)
        
    if cv2.waitKey(1)==13:
        break
cap.release()
cv2.destroyAllWindows()